name: CV Sync Automation
on:
  schedule:
    - cron: '0 9 * * *'  # Tous les jours à 9h
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  sync-cv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'  # Version stable sans le bug crypto
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install googleapis pdf-parse
      
    - name: Run CV Sync
      env:
        GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
        GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
        GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      run: node scripts/cv-sync.js
      
    - name: Notify success
      if: success()
      run: echo "✅ CV synchronization completed successfully"
      
    - name: Notify failure
      if: failure()
      run: echo "❌ CV synchronization failed"
